#!@runtimeShell@
set -u

# NetworkManager dispatcher hook generated by
# networkmanager-bridge-address-cascade.nix.
#
# NixOS/NetworkManager own the bridge profiles. This hook only performs the
# runtime-only decision that cannot be expressed in a profile: selecting a stable
# IPv4 address after the DHCP server has identified the LAN.

# Bridge interface this generated hook is allowed to modify.
configured_bridge_interface=@bridgeInterfaceShell@

# NetworkManager profile ID for the static no-DHCP fallback. When this profile
# is active, NetworkManager has already applied the fallback address.
configured_no_dhcp_fallback_profile=@noDhcpFallbackProfileIdShell@

# Space-separated CIDR list of every static address managed by this hook.
# Addresses outside this list are intentionally left untouched.
managed_static_cidr_list=@managedStaticCidrListShell@

# Absolute path to nmcli from the Nix store.
nmcli=@nmcliShell@

# Absolute path to iproute2's `ip` from the Nix store.
ip=@ipShell@

# Absolute path to awk from the Nix store.
awk=@awkShell@

# Absolute path to logger from the Nix store.
logger=@loggerShell@

# NetworkManager passes the interface name as dispatcher argument 1.
networkmanager_interface_name="${1:-}"

# NetworkManager passes the event name as dispatcher argument 2.
networkmanager_dispatcher_event="${2:-}"

# Ignore dispatcher events for every interface except the configured bridge.
if [ "$networkmanager_interface_name" != "$configured_bridge_interface" ]; then
  exit 0
fi

# Run only when IPv4 DHCP state may have become available or changed.
case "$networkmanager_dispatcher_event" in
  up|dhcp4-change)
    ;;
  *)
    exit 0
    ;;
esac

# Read the active NetworkManager profile ID for the bridge. This distinguishes
# the no-DHCP fallback profile from the normal DHCP profile.
active_networkmanager_profile_id="$("$nmcli" -g GENERAL.CONNECTION device show "$networkmanager_interface_name" 2>/dev/null || true)"

# If the fallback profile is active, NetworkManager already set the desired
# static address. Exiting here avoids fighting the declarative fallback profile.
if [ "$active_networkmanager_profile_id" = "$configured_no_dhcp_fallback_profile" ]; then
  "$logger" -t networkmanager-address-cascade "$configured_bridge_interface: keeping no-DHCP fallback profile $configured_no_dhcp_fallback_profile"
  exit 0
fi

# Prefer the DHCP server identifier exported directly by NetworkManager's
# dispatcher environment.
observed_dhcp_server_address="${DHCP4_DHCP_SERVER_IDENTIFIER:-}"

# Some NetworkManager/DHCP combinations expose a shorter variable name instead.
if [ -z "$observed_dhcp_server_address" ]; then
  observed_dhcp_server_address="${DHCP4_DHCP_SERVER_ID:-}"
fi

# Fall back to nmcli inspection when the dispatcher environment does not expose
# the DHCP server identifier.
if [ -z "$observed_dhcp_server_address" ]; then
  observed_dhcp_server_address="$("$nmcli" -t -f DHCP4.OPTION device show "$networkmanager_interface_name" 2>/dev/null | "$awk" '
    /dhcp_server_identifier|server_identifier|dhcp-server-identifier/ {
      sub(/^[^=]*= */, "", $0)
      print
      exit
    }
  ')"
fi

# Empty by default means "unknown DHCP server, keep the DHCP lease".
selected_static_address=""

# Generated ordered cascade: DHCP server address -> preferred static address.
case "$observed_dhcp_server_address" in
@dhcpServerCaseBody@
  *)
    ;;
esac

# Unknown DHCP server branch. Remove only addresses managed by this hook, then
# leave NetworkManager's ordinary DHCP lease in place.
if [ -z "$selected_static_address" ]; then
  for managed_static_cidr in $managed_static_cidr_list; do
    # Ignore deletion failures because an address may not be present.
    "$ip" -4 address del "$managed_static_cidr" dev "$networkmanager_interface_name" 2>/dev/null || true
  done

  "$logger" -t networkmanager-address-cascade "$configured_bridge_interface: leaving DHCP address from server $observed_dhcp_server_address"
  exit 0
fi

# CIDR selected by the cascade for the known DHCP server.
selected_static_cidr="$selected_static_address/@prefixLength@"

# Remove stale managed static addresses from previous LANs before applying the
# selected one.
for managed_static_cidr in $managed_static_cidr_list; do
  if [ "$managed_static_cidr" != "$selected_static_cidr" ]; then
    # Ignore deletion failures because an address may not be present.
    "$ip" -4 address del "$managed_static_cidr" dev "$networkmanager_interface_name" 2>/dev/null || true
  fi
done

# Add or update the preferred static address for this LAN.
"$ip" -4 address replace "$selected_static_cidr" dev "$networkmanager_interface_name"

# Remove the dynamic DHCP lease address so the bridge exposes only the preferred
# static address for known LANs.
"$ip" -o -4 address show dev "$networkmanager_interface_name" scope global dynamic \
  | "$awk" '{ print $4 }' \
  | while IFS= read -r dynamic_dhcp_cidr; do
      if [ -n "$dynamic_dhcp_cidr" ] && [ "$dynamic_dhcp_cidr" != "$selected_static_cidr" ]; then
        # Ignore deletion failures because DHCP state may change underneath NM.
        "$ip" -4 address del "$dynamic_dhcp_cidr" dev "$networkmanager_interface_name" 2>/dev/null || true
      fi
    done

# Record the final decision in the journal for debugging LAN detection.
"$logger" -t networkmanager-address-cascade "$configured_bridge_interface: set $selected_static_cidr for DHCP server $observed_dhcp_server_address"
